# Generated by Django 4.1 on 2023-08-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='person_name',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='유저 닉네임'),
        ),
    ]
